### ISSUE TITLE
代码块中 vue 有关插槽的代码渲染错误。

### ISSUE THREAD

**Issue by DAWN0ER** [cayxc/Mdmdt#10]
![image](https://github.com/user-attachments/assets/b6d215c2-0e8c-4a0a-be18-1f2d310fbc52)
typora 的默认主题没有这个问题，麻烦作者修复一下。

**Comment by cayxc** [comment]
你好，感谢建议，问题已修复，请[下载最新版本](https://github.com/cayxc/Mdmdt/tags)
<img width="1105" alt="截屏2024-12-23 23 00 55" src="https://github.com/user-attachments/assets/2730224a-10e7-4b88-99a4-2cf14a2501fb" />
