### ISSUE TITLE
 tip、caution、alert、warning 等引用框样式不生效的问题

### ISSUE THREAD

**Issue by gaoyangwind** [cayxc/Mdmdt#2]
作者您好，感谢您的分享。我在使用过程中发现如下问题，麻烦您解答。

Typora v0.9.96 (beta) & v.0.9.71，Win10 系统，mdmdt-dark & mdmdt-light 均发现引用框样式不生效的情况，例如 tip、caution、alert、warning 等引用框的样式不生效，只有 markdown 语法原本的引用标记（>）样式生效。请问是什么原因，该如何解决？

![image](https://github.com/user-attachments/assets/7764bc0f-13d0-4c54-927f-b31a1e4895e4)

**Comment by cayxc** [comment]
您好，Typora在windows环境下的引用框目前只有一个样式。因为：Typora在windows和mac环境下的文档结构有一些区别，暂时解决不了！

**Comment by gaoyangwind** [comment]
收到，原来是我使用的 Typora 版本过低的原因。Github 风格警报框特性是从 1.8 版本才引入的。多谢您回复解惑！

P.S：知乎上给您留言的也是我，您可忽略。
