### ISSUE TITLE
增加公式支持 

### ISSUE THREAD

**Issue by ZJunSong** [cayxc/Mdmdt#5]
感谢作者的分享。我常在黑暗主题下编写博客（包含大量数学公式、代码）。
目前的黑暗模式有几个可以改进的地方：
+ 黑暗主题中，鼠标在公式框**悬停**时全白，看不到公式
+ 黑暗主题中，公式框编辑模式下出现白边
+ 黑暗主题中，公式框和代码框编辑模式下光标为黑色，与背景对比度太低，不明显
+ 公式框编辑模式下的源代码字体非常难看，希望改一下

![image](https://github.com/user-attachments/assets/d79bad6f-76ae-4402-89f8-55796d9ee9d6)
![image](https://github.com/user-attachments/assets/1b579eef-d6d5-4bdd-a031-73e3d4c0d3e6)

**Comment by cayxc** [comment]
[感谢建议，目前相关问题已优化。请选择最新版本下载[Mdmdt v0.1.16](https://github.com/cayxc/Mdmdt/releases/tag/v0.1.16)
关于字体难看问题：默认字体选择优先级："PingFang SC", "Helvetica Neue", Helvetica, "Microsoft YaHei"
建议下载`PingFang和monospace`字体，代码使用的是monospace字体。
