### ISSUE TITLE
请问一下，这个怎么更换字体啊？

### ISSUE THREAD

**Issue by web1230** [cayxc/Mdmdt#7]

**Comment by cayxc** [comment]
1. 正文替换字体，找到：`body {font-family: "PingFang SC", Helvetica, "Helvetica Neue", "Microsoft YaHei", Arial, sans-serif !important;}`和`body.os-windows{
  font-family: Helvetica, "Helvetica Neue", "Microsoft YaHei", Arial, sans-serif !important;
}`，在 `font-family:`添加你想使用的字体，如：`font-family:想使用的字体, Helvetica, "Helvetica Neue", "Microsoft YaHei", Arial, sans-serif !important;`
2. 想要替换代码的字体，找到：`code,tt{...}`和`pre{...}`添加`font-family: 想使用的字体, !important;`，然后同前面一样修改`.os-windows pre,.os-windows code {...}`中的font-family。
