### ISSUE TITLE
中划线无法对齐大于号中部，画不出好看的箭头

### ISSUE THREAD

**Issue by Matty12138** [cayxc/Mdmdt#9]
![截图 2024-12-23 14-39-12](https://github.com/user-attachments/assets/ba1943bc-6417-49fd-8a64-407522085b5e)

**Comment by cayxc** [comment]
你好，这是字体的原因，重新调整了字体方案，请下载最新版本
<img width="340" alt="截屏2024-12-23 19 27 29" src="https://github.com/user-attachments/assets/0f0ed990-87b8-4d5f-a530-6483c9217279" />
